version: 2.1
orbs:
  node: circleci/node@5.1.0
  cypress: cypress-io/cypress@3.1.3
jobs:
  build and test:
    executor: node/default
    docker:
      - image: cypress/base:16
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm 
      - run:
          command: npm install
          name: Install Dependencies
      - run:
          command: npx expo start
          background: true
          name: Start Expo Server
      - run:
          command: sleep 30 # Adjust the wait time as needed
          name: Wait for Expo Server
      - cypress/run-tests:
          start-command: 'CI=false npx cypress open'
          cypress-command: 'npx cypress run'
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  test_my_app:
    jobs:
      - build and test
