version: 2.1
orbs:
  node: circleci/node@5.1.0
  cypress: cypress-io/cypress@3.1.3
jobs:
  build-and-test:
    executor: node/default
    docker:
      - image: cypress/base:16
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install
          name: install dependencies
      - run:
          command: npm install -g expo-cli
          name: install expo-cli
      - run:
          command: npx expo install --fix
          name: update dependencies
      - run:
          name: Start Expo
          command: expo start --web --non-interactive
          background: true
      - cypress/run-tests:
          cypress-command: 'npm run cy:run --'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-test





